import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TopSection from "@/components/TopSection";
import SearchBarForSM from "@/components/SearchBarForSM";
import Menubar from "@/components/Menubar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shop Store",
  description: "Generated by create next app",
  icons: {
    icon : '/icon.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopSection/>
        <Navbar/>
        <SearchBarForSM/>
        <Menubar/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
